### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [keigan-motor/Arduino-I2C-KM1#2]
In the file "src/KM1_I2C.cpp" there is a `Wire.beginTransmission()` before the `Wire.requestFrom()` and a `Wire.endTransmission()` after it.
Those `Wire.beginTransmission()` and `Wire.endTransmission()` are at the moment at line 84 and 94 and can be removed.

Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by okhiroyuki** [comment]
fix https://github.com/keigan-motor/Arduino-I2C-KM1/commit/404757e96c79c08b458f046fff03cde7aa7d0a2d

**Comment by keigan-motor** [comment]
Dear Koepel
Thank you for your comment.
I fixed it.

Thank you so much.

Takashi
